version: "3"
services:
  website:
    image: ghcr.io/jonas-de/copacabela-anmeldung:payment
    build: .
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT}
      - PAYLOAD_SECRET_KEY=${PAYLOAD_SECRET_KEY}
      - MONGO_URL=${MONGO_URL}
      - NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL}
      - PAYLOAD_PUBLIC_SERVER_URL=${PAYLOAD_PUBLIC_SERVER_URL}

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - data_db:/data/db
      - data_config:/data/config

volumes:
  data_db:
  data_config:
