version: "3"
services:
  website:
    image: ghcr.io/jonas-de/copacabela-anmeldung
    build: .
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      - PORT=${PORT}
      - PAYLOAD_SECRET_KEY=${PAYLOAD_SECRET_KEY}
      - MONGO_URL=${MONGO_URL}
      - NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL}
      - PAYLOAD_PUBLIC_SERVER_URL=${PAYLOAD_PUBLIC_SERVER_URL}
      - PAYLOAD_LICENSE=${PAYLOAD_LICENSE}
      - PAYLOAD_CORS=${PAYLOAD_CORS}
      - PAYLOAD_CSRF=${PAYLOAD_CSRF}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_PORT=${SMTP_PORT}
      - VIRTUAL_HOST=anmeldung.copacabela.de
      - LETSENCRYPT_HOST=anmeldung.copacabela.de
    networks:
      - default
      - nginx_proxy

  mongo:
    image: mongo:4
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - data_db:/data/db
      - data_configdb:/data/configdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    networks:
      - default

volumes:
  data_db:
  data_configdb:

networks:
  nginx_proxy:
    external: true
