version: "3"
services:
  website:
    image: ghcr.io/jonas-de/copacabela-anmeldung:belewe
    build: .
    restart: unless-stopped
    environment:
      - PORT=${PORT}
      - PAYLOAD_SECRET_KEY=${PAYLOAD_SECRET_KEY}
      - MONGO_URL=${MONGO_URL}
      - NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL}
      - PAYLOAD_PUBLIC_SERVER_URL=${PAYLOAD_PUBLIC_SERVER_URL}
      - PAYLOAD_CORS=${PAYLOAD_CORS}
      - PAYLOAD_CSRF=${PAYLOAD_CSRF}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_PORT=${SMTP_PORT}
      - VIRTUAL_HOST=belewe.dpsg1312.de
      - LETSENCRYPT_HOST=belewe.dpsg1312.de
    networks:
      - shared-mongo
      - nginx_proxy

networks:
  nginx_proxy:
    external: true
  shared-mongo:
    external: true
