/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participantscontroller".
 */
export interface TeilnehmendenverwalterIn {
  id: string;
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  name: string;
  tribe:
    | '131202'
    | '131203'
    | '131204'
    | '131206'
    | '131207'
    | '131208'
    | '131209'
    | '131210'
    | '131212'
    | '131213'
    | '131214'
    | '1312';
  level: 'woelflinge' | 'jupfis' | 'pfadis' | 'rover' | 'all';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participants".
 */
export interface TeilnehmerIn {
  id: string;
  gender: 'female' | 'male' | 'divers';
  firstName: string;
  lastName: string;
  tribe:
    | '131202'
    | '131203'
    | '131204'
    | '131206'
    | '131207'
    | '131208'
    | '131209'
    | '131210'
    | '131212'
    | '131213'
    | '131214';
  birthDate: string;
  eatingBehaviour: 'vegan' | 'vegetarian' | 'meat';
  foodIntolerances?: string;
  swimmer: boolean;
  state: 'new' | 'confirmed' | 'cancelled';
  level?: 'woelflinge' | 'jupfis' | 'pfadis' | 'rover';
  registration?: string | Anmeldung;
  photopermission?: string | Fotoerlaubnis;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrationforms".
 */
export interface Anmeldung {
  id: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photopermissions".
 */
export interface Fotoerlaubnis {
  id: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
}
