/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    participantscontroller: Participantscontroller;
    participants: Participant;
  };
  globals: {};
}
export interface Participantscontroller {
  id: string;
  name: string;
  tribe:
    | '131202'
    | '131203'
    | '131204'
    | '131206'
    | '131207'
    | '131208'
    | '131209'
    | '131210'
    | '131212'
    | '131213'
    | '1312';
  level: 'woelflinge' | 'jupfis' | 'pfadis' | 'rover' | 'all' | 'kitchen' | 'strandkorb';
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface Participant {
  id: string;
  orderId: number;
  firstName: string;
  lastName: string;
  birthDate: string;
  gender: 'female' | 'male' | 'divers';
  email: string;
  phoneNumber?: string;
  address: {
    street: string;
    zipCode: string;
    city: string;
  };
  tribe:
    | '131202'
    | '131203'
    | '131204'
    | '131206'
    | '131207'
    | '131208'
    | '131209'
    | '131210'
    | '131212'
    | '131213'
    | '1312';
  level: 'woelflinge' | 'jupfis' | 'pfadis' | 'rover' | 'none';
  food: {
    intolerances?: string;
  };
  diseases?: string;
  healthInsurance: 'gkv' | 'pkv';
  comments?: string;
  juleica: {
    number?: string;
    terminates?: string;
  };
  clearance: {
    idNumber?: string;
    nami?: boolean;
  };
  state: 'new' | 'confirmed' | 'cancelled';
  cancelledAt?: string;
  confirmationToken: string;
  createdAt: string;
  updatedAt: string;
}
